### ISSUE TITLE
Tracking issue for FlowSOM interoperability

### ISSUE THREAD

**Issue by berombau** [saeyslab/harpy#6]
Clustering with FlowSOM is possible and cell clustering with napari-cluster-plotter (https://github.com/saeyslab/harpy/blob/main/experiments/example_of_cluster_plotter.ipynb) is possible. It would be interesting to view the FlowSOM tree in a similar widget and allow labeling of the metaclusters on the tree (similar to Pixie pipeline notebook GUI, but with the imaging data in napari instead of Mantis). 

- [ ] create Widget class
- [ ] button to cluster
- [ ] button to plot FlowSOM tree
- [ ] button to get labels in table
- [ ] select with lasso tool
- [ ] view selection on images
- [ ] allow renaming metacluster labels to cell type names
- [ ] plot cluster heatmap similar to to Pixie pipeline
